site_name: StaphSCAN
site_url: https://staphscan.readthedocs.io/
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: 
    - Overview: modules.md
    - Assembly: assembly.md
    - Typing: typing.md                    
    - Resistance: resistance.md 
    - Virulence: virulence.md   
theme:
  name: material

markdown_extensions:
  - admonition

  - codehilite
